/**
 * IDE Rules Generator
 *
 * Generates rule files for AI coding assistants (Cursor, Copilot, Augment)
 * based on scan/heal results so they avoid repeating detected issues.
 */

import { writeFileSync, mkdirSync } from 'node:fs';
import { resolve, relative } from 'node:path';
import type { AggregateScore, FileScore } from '../scorer/scoring-engine.js';
import type { HealReport } from './auto-fix-engine.js';

// ─── Types ─────────────────────────────────────────────────────────

export interface IDERulesOptions {
  projectRoot: string;
  /** Scan report (required) */
  report: AggregateScore;
  /** Optional heal report (includes fix details) */
  healReport?: HealReport;
}

// ─── Generator ─────────────────────────────────────────────────────

export class IDERulesGenerator {
  /**
   * Generate IDE rule files for all supported assistants.
   */
  generateAll(options: IDERulesOptions): { path: string; content: string }[] {
    const files: { path: string; content: string }[] = [];

    const cursorRules = this.generateCursorRules(options);
    files.push({ path: '.cursor/rules/ocr-fixes.md', content: cursorRules });

    const copilotInstructions = this.generateCopilotInstructions(options);
    files.push({ path: '.github/copilot-instructions.md', content: copilotInstructions });

    const augmentInstructions = this.generateAugmentInstructions(options);
    files.push({ path: '.augment/instructions.md', content: augmentInstructions });

    return files;
  }

  /**
   * Write IDE rule files to disk.
   */
  writeAll(options: IDERulesOptions): string[] {
    const files = this.generateAll(options);
    const writtenPaths: string[] = [];

    for (const file of files) {
      const fullPath = resolve(options.projectRoot, file.path);
      mkdirSync(resolve(options.projectRoot, file.path, '..'), { recursive: true });
      writeFileSync(fullPath, file.content, 'utf-8');
      writtenPaths.push(fullPath);
    }

    return writtenPaths;
  }

  /**
   * Generate Cursor rules file.
   */
  generateCursorRules(options: IDERulesOptions): string {
    const lines: string[] = [];
    lines.push('---');
    lines.push('description: Open Code Review — AI code quality rules');
    lines.push('globs: ');
    lines.push('  - "**/*.ts"');
    lines.push('  - "**/*.js"');
    lines.push('  - "**/*.tsx"');
    lines.push('  - "**/*.jsx"');
    lines.push('  - "**/*.py"');
    lines.push('  - "**/*.java"');
    lines.push('  - "**/*.go"');
    lines.push('  - "**/*.kt"');
    lines.push('---');
    lines.push('');
    lines.push('# AI Code Quality Rules (auto-generated by Open Code Review)');
    lines.push('');
    lines.push(`Last updated: ${new Date().toISOString()}`);
    lines.push(`Overall score: ${options.report.overallScore}/100 (Grade: ${options.report.grade})`);
    lines.push('');
    lines.push('## Issue Patterns to Avoid');
    lines.push('');

    const issuePatterns = this.extractPatterns(options);
    if (issuePatterns.length > 0) {
      for (const pattern of issuePatterns) {
        lines.push(`### ${pattern.category}`);
        lines.push(`${pattern.description}`);
        lines.push('');
        if (pattern.examples.length > 0) {
          lines.push('Examples found in this project:');
          for (const ex of pattern.examples.slice(0, 5)) {
            lines.push(`- \`${ex.file}\` (line ${ex.line}): ${ex.message}`);
          }
          lines.push('');
        }
      }
    } else {
      lines.push('No issues detected. Keep following best practices!');
      lines.push('');
    }

    // Add heal-specific rules
    if (options.healReport) {
      lines.push('## Recently Fixed Issues');
      lines.push('');
      lines.push('The following issues were auto-fixed. Do NOT reintroduce them:');
      lines.push('');
      for (const result of options.healReport.results) {
        if (result.patches.length > 0) {
          lines.push(`- **${result.file}** (score: ${result.originalScore} → ${result.fixedScore})`);
        }
      }
      lines.push('');
    }

    lines.push('## General Guidelines');
    lines.push('');
    lines.push('1. Only import packages that exist in the project dependencies');
    lines.push('2. Use up-to-date APIs — check for deprecation warnings');
    lines.push('3. Add proper error handling to all async operations');
    lines.push('4. Remove unused imports and variables');
    lines.push('5. Use `crypto.randomInt()` instead of `Math.random()` for security-sensitive operations');
    lines.push('6. Use `params` instead of `query` for URL parameters unless intentionally using query strings');
    lines.push('7. Add proper TypeScript types — avoid `any` when possible');
    lines.push('8. Handle edge cases and empty states in all functions');

    return lines.join('\n');
  }

  /**
   * Generate GitHub Copilot instructions file.
   */
  generateCopilotInstructions(options: IDERulesOptions): string {
    const lines: string[] = [];
    lines.push('# GitHub Copilot Instructions (auto-generated by Open Code Review)');
    lines.push('');
    lines.push(`Overall code quality score: ${options.report.overallScore}/100`);
    lines.push('');

    const issuePatterns = this.extractPatterns(options);
    if (issuePatterns.length > 0) {
      lines.push('## Known Issue Patterns — Avoid These');
      lines.push('');
      for (const pattern of issuePatterns) {
        lines.push(`### ${pattern.category}`);
        lines.push(pattern.description);
        lines.push('');
        for (const ex of pattern.examples.slice(0, 3)) {
          lines.push(`- ❌ \`${ex.file}:${ex.line}\` — ${ex.message}`);
        }
        lines.push('');
      }
    }

    lines.push('## Coding Rules for This Project');
    lines.push('');
    lines.push('- Only use imports that exist in package.json / requirements.txt / go.mod');
    lines.push('- Verify API methods exist before using them');
    lines.push('- Add try/catch to all async/await calls');
    lines.push('- Use `crypto` module for secure random number generation');
    lines.push('- Type all function parameters and return values');
    lines.push('- Remove TODO/FIXME comments before committing');
    lines.push('- Prefer explicit error types over generic `catch`');

    return lines.join('\n');
  }

  /**
   * Generate Augment instructions file.
   */
  generateAugmentInstructions(options: IDERulesOptions): string {
    const lines: string[] = [];
    lines.push('# Augment Coding Assistant Instructions');
    lines.push('');
    lines.push(`Code quality score: ${options.report.overallScore}/100. Auto-generated by Open Code Review.`);
    lines.push('');

    const issuePatterns = this.extractPatterns(options);
    if (issuePatterns.length > 0) {
      lines.push('## Frequently Detected Issues');
      lines.push('');
      for (const pattern of issuePatterns) {
        lines.push(`**${pattern.category}**: ${pattern.description}`);
      }
      lines.push('');
    }

    lines.push('## Rules');
    lines.push('');
    lines.push('- No hallucinated imports or APIs');
    lines.push('- Use current, non-deprecated APIs');
    lines.push('- Always handle errors properly');
    lines.push('- Maintain consistent code style');
    lines.push('- Avoid over-engineering — keep it simple');
    lines.push('- Add proper types and null checks');

    return lines.join('\n');
  }

  /**
   * Extract common issue patterns from the report.
   */
  private extractPatterns(options: IDERulesOptions): Array<{
    category: string;
    description: string;
    examples: Array<{ file: string; line: number; message: string }>;
  }> {
    // Extract patterns from file dimensions (legacy FileScore format)
    const patterns = new Map<string, { description: string; examples: Array<{ file: string; line: number; message: string }> }>();

    const categoryDescriptions: Record<string, string> = {
      completeness: 'Hallucinated imports, references to non-existent packages/APIs, incomplete code',
      coherence: 'Logic gaps, context inconsistencies, broken control flow',
      consistency: 'Style inconsistencies, mixed patterns, architectural drift',
      conciseness: 'Code duplication, over-engineering, unnecessary abstraction',
    };

    for (const file of options.report.files) {
      const dims = [
        { key: 'completeness', dim: file.dimensions.completeness },
        { key: 'coherence', dim: file.dimensions.coherence },
        { key: 'consistency', dim: file.dimensions.consistency },
        { key: 'conciseness', dim: file.dimensions.conciseness },
      ];

      for (const { key, dim } of dims) {
        if (dim.issueCount > 0) {
          if (!patterns.has(key)) {
            patterns.set(key, {
              description: categoryDescriptions[key] || key,
              examples: [],
            });
          }
          const pattern = patterns.get(key)!;
          for (const detail of dim.details.slice(0, 3)) {
            pattern.examples.push({
              file: file.file,
              line: 0,
              message: detail,
            });
          }
        }
      }
    }

    return Array.from(patterns.entries()).map(([category, data]) => ({
      category,
      ...data,
    }));
  }
}

export default IDERulesGenerator;
